# Generated by Django 2.1.3 on 2018-11-23 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('rating', models.SmallIntegerField(choices=[(1, 'Awesome'), (2, 'Good'), (3, 'Normal'), (4, 'Bad')], help_text='Choose wisely')),
                ('is_released', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('is_capital', models.BooleanField()),
                ('area', models.BigIntegerField(blank=True, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
            },
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': '大洲',
                'verbose_name_plural': '大洲',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(help_text='ISO 3166-1 alpha-2 - two character country code', max_length=2)),
                ('independence_day', models.DateField(blank=True, null=True)),
                ('area', models.BigIntegerField(blank=True, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Try and enter few some more lines')),
                ('architecture', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('continent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='demo.Continent')),
            ],
            options={
                'verbose_name': '国家',
                'verbose_name_plural': '国家',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('rating', models.SmallIntegerField(choices=[(1, 'Awesome'), (2, 'Good'), (3, 'Normal'), (4, 'Bad')], default=2)),
                ('description', models.TextField(blank=True)),
                ('is_released', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('help_text', models.CharField(help_text='Enter fully qualified name', max_length=64)),
                ('multiple_in_row', models.CharField(help_text='Help text for multiple', max_length=64)),
                ('textfield', models.TextField(blank=True, help_text='Try and enter few some more lines', verbose_name='Autosized textfield')),
                ('readonly_field', models.CharField(default='Some value here', max_length=127)),
                ('multiple2', models.CharField(blank=True, max_length=10)),
                ('date', models.DateField(blank=True, null=True)),
                ('date_and_time', models.DateTimeField(blank=True, null=True)),
                ('time_only', models.TimeField(blank=True, null=True, verbose_name='Time')),
                ('date_widget', models.DateField(blank=True, null=True)),
                ('datetime_widget', models.DateTimeField(blank=True, null=True)),
                ('collapsed_param', models.BooleanField(default=False)),
                ('boolean', models.BooleanField(default=True)),
                ('boolean_with_help', models.BooleanField(default=False, help_text='Boolean field with help text')),
                ('horizontal_choices', models.SmallIntegerField(choices=[(1, 'Awesome'), (2, 'Good'), (3, 'Normal'), (4, 'Bad')], default=1, help_text='Horizontal choices look like this')),
                ('vertical_choices', models.SmallIntegerField(choices=[(1, 'Hot'), (2, 'Normal'), (3, 'Cold')], default=2, help_text='Some help on vertical choices')),
                ('choices', models.SmallIntegerField(choices=[(1, 'Tall'), (2, 'Normal'), (3, 'Short')], default=3, help_text='Help text')),
                ('html5_color', models.CharField(blank=True, max_length=7, null=True)),
                ('html5_number', models.IntegerField(blank=True, null=True)),
                ('html5_date', models.DateField(blank=True, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.Country')),
                ('country2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showcase_country2_set', to='demo.Country', verbose_name='Django Select 2')),
                ('raw_id_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='showcase_raw_set', to='demo.Country')),
            ],
            options={
                'verbose_name': '玻璃柜台',
                'verbose_name_plural': '玻璃柜台',
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='showcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Showcase'),
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Country'),
        ),
        migrations.AddField(
            model_name='book',
            name='showcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Showcase'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'country')},
        ),
    ]
